### ISSUE TITLE
Crash on run with OpenJDK Java 8

### ISSUE THREAD

**Issue by aswheaton** [Querz/mcaselector#6]
Running the jar using OpenJDK Java 8 rather than the Oracle's Java 8 crashes immediately, with the exception:

```
Exception in thread "main" java.lang.NoClassDefFoundError: javafx/scene/paint/Color
	at net.querz.mcaselector.Config.<clinit>(Config.java:12)
	at net.querz.mcaselector.Main.main(Main.java:11)

Caused by: java.lang.ClassNotFoundException: javafx.scene.paint.Color
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 2 more
```

It's not clear whether this error is due to the use of OpenJDK or if you intend to support anything other than Oracle-brewed Java, but thought I would post this here.

**Comment by Querz** [comment]
I haven't tested the MCA Selector with OpenJDK, that's why the installation instructions only contain a link to Oracle Java.
The stacktrace suggests that you are probably missing JavaFX.
JavaFX comes with Oracle Java by default, I am not sure about OpenJDK though.
I will look into this and add instructions about OpenJDK to the Readme, because it appears that a good amount of people are using OpenJDK

**Comment by Querz** [comment]
Are you using [AdoptOpenJDK](https://github.com/AdoptOpenJDK/openjdk-build)? Because it does not seem to contain JavaFX: See [this issue](https://github.com/AdoptOpenJDK/openjdk-build/issues/577). There are some workarounds mentioned in the issue that involve copying files over from the Oracle JDK.
I added a warning to the Readme that you need JavaFX, because I will not write a full article on how to add JavaFX to AdoptOpenJDK :)

**Comment by aswheaton** [comment]
I am using the default OpenJDK distribution which is in the [Ubuntu repositories](https://packages.ubuntu.com/xenial/default-jdk). I'm pretty sure this comes from the upstream Debian build, which might be AdoptOpenJDK, but that is a little beyond my depth. Most users of an alternative Java will be using the one in the Debian repositories, however, so I have found a solution which will work for most users of an open source JDK downstream of Debian. Apparently, JavaFX no longer ships with the `default-jdk` package, but an [equivalent package](https://packages.ubuntu.com/xenial/openjfx) `openjfk` is still in the repositories. Installing this package alongside your OpenJDK distribution solves the problem. For me, this was just a simple matter of typing:

`$ sudo apt install default-jdk openjfx`

Into the terminal. But users on any Linux distribution downstream of Debian should just be able to replace `apt install` with the package manager of their choice. After doing this, I was able to run the jar without issue! Great little project!

**Comment by rhonda** [comment]
I can confirm that installing openjfx alongside the openjdk jre package fixes this.  I guess you can close this issue with adding that hint into the readme. :)

Thanks for sharing this great and useful piece of software to use!

**Comment by Querz** [comment]
Thanks! I personally never had the time to tinker too much with Debian, so I'm glad that someone figured this out. I merged #7 and I consider this as solved then :)

**Comment by Harpz** [comment]
Was having issues running this so ran suggested above _"sudo apt install default-jdk openjfx"_ and it didn't solve the issue for me for some reason, anyone able to point me in the right direction please?

java -version 
openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment (build 11.0.2+9-Ubuntu-3ubuntu118.04.3)

java -jar mcaselector-1.6.jar 
Exception in thread "main" java.lang.NoClassDefFoundError: javafx/scene/paint/Color
	at net.querz.mcaselector.Config.<clinit>(Config.java:12)
	at net.querz.mcaselector.Main.main(Main.java:11)
Caused by: java.lang.ClassNotFoundException: javafx.scene.paint.Color
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 2 more

**Comment by aswheaton** [comment]
Seems like you are running a much more recent version of OpenJDK, probably from the PPA. I have:

`java -version
openjdk version "1.8.0_191"
OpenJDK Runtime Environment (build 1.8.0_191-8u191-b12-2ubuntu0.16.04.1-b12)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)`

It's possible that this version won't play nice with the version of openjfx in the repositories. Try removing the PPA and then reinstalling openjdk with the command I gave above.

**Comment by rhonda** [comment]
@Harpz Which version of openjfx do you have installed? Because it has to match the openjdk version. You can find that out through a "dpkg -l default-jre default-jdk openjfx" (default-jre also included, because actually that's enough, you don't need the fullblown jdk (Java Development Kit) but only the jre (Java Runtime Environment) to use it. For use with openjdk 11.0.2 you need openjfx 11.0.2 too.

**Comment by Harpz** [comment]
Hi rhonda

First of all thanks for the help, I purged the currently installed packages with _sudo purge default-jre default-jdk openjfx_ then reinstalled them with _sudo apt install default-jre openjfx_

I now get the following info

java -version 
openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment (build 11.0.2+9-Ubuntu-3ubuntu118.04.3)
OpenJDK 64-Bit Server VM (build 11.0.2+9-Ubuntu-3ubuntu118.04.3, mixed mode, sharing)

sudo dpkg -l default-jre openjfx
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                    Version          Architecture     Description
+++-=======================-================-================-====================================================
ii  default-jre             2:1.11-68ubuntu1 amd64            Standard Java or Java compatible Runtime
ii  openjfx                 11.0.2+1-1~18.04 amd64            JavaFX/OpenJFX - Rich client application platform 

I still get the same error as before, any pointers, thanks.

**Comment by aswheaton** [comment]
If you look at the version output you'll see that you're still running the same version of OpenJDK. Like I said above, you have probably installed a more recent version by adding a PPA, probably [this one](https://launchpad.net/~openjdk-r/+archive/ubuntu/ppa). As long as you have added this PPA in your repositories, `apt` will install a version from that source whenever you run `apt install openjdk`, not the more stable version which is in the repositories by default. You need to remove this PPA from your sources, and _then_ reinstall `openjdk`. Try the following:

`sudo apt purge default-jre default-jdk openjfx`
`sudo add-apt-repository --remove ppa:PPA_Name/ppa`
`sudo apt install default-jre openjfx`
OR
`sudo apt install default-jdk openjfx`

In the future, try to learn how repositories and your package manager work, and to keep track of changes you make to your system. It will save you a lot of headache.

**Comment by Harpz** [comment]
Hi ashwheaton

Tried looking for anything java but couldn't see anything, probably missed it, 

lsb_release -a  shows im running Ubuntu 18.04.2 LTS

a cat of /etc/apt/sources.list as requested
https://pastebin.com/Y9jBWjdY

I ran _sudo_ apt purge default-jre default-jdk openjfx_ and that removed all but java -version still showed 11.0.2 installed so i ran _sudo apt purge openjdk-11-jre*_ to remove it and now i have:

java -version
openjdk version "1.8.0_191"
OpenJDK Runtime Environment (build 1.8.0_191-8u191-b12-2ubuntu0.18.04.1-b12)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)

The problem i have now is when i run _sudo apt install default-jre openjfx_ i get the following, its trying to install 11.0.2 again:

Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  default-jre-headless openjdk-11-jre openjdk-11-jre-headless
Suggested packages:
  fonts-ipafont-gothic fonts-ipafont-mincho fonts-wqy-microhei | fonts-wqy-zenhei
The following NEW packages will be installed
  default-jre default-jre-headless openjdk-11-jre openjdk-11-jre-headless openjfx
0 to upgrade, 5 to newly install, 0 to remove and 0 not to upgrade.
Need to get 37.2 MB of archives.
After this operation, 170 MB of additional disk space will be used.
Do you want to continue? [Y/n] 

Got to be a source somewhere that is trying to pull it in,

**Comment by Taranchul** [comment]
I beg your forgiveness for replying to a closed issue, but I also had this problem and I found a solution that I want to share. The problem seems to be that the current releases of Debian and its derivatives like Ubuntu ship with OpenJDK 11 as the standard Java version. Although they provide optional OpenJDK 8 packages in their official repositories, their only package for OpenJFX is version 11. To make matters worse, their OpenJDK 11 and OpenJFX 11 have a version mismatch. The former ist version 11.0.3, whereas the latter is version 11.0.2. I don't know if that can create issues with Java 11 applications.

Fortunately, I found a solution for Ubuntu 18.04.x in [comment #18 of this bugreport](https://bugs.launchpad.net/ubuntu/+source/openjfx/+bug/1799946) that works for me:

1. Install the Java 8 JRE with "sudo apt install openjdk-8-jre" (or openjdk-8-jdk for the development kit)
2. If you also have Java 11 installed, use "sudo update-alternatives --config java" to switch to Java 8.
3. Downgrade OpenJFX to version 8 with "sudo apt install openjfx=8u161-b12-1ubuntu2 libopenjfx-java=8u161-b12-1ubuntu2 libopenjfx-jni=8u161-b12-1ubuntu2"

**Comment by 0xfeeddeadbeef** [comment]
I am assuming JRE 8+ requirement means that mcaselector should be compatible with JDK 13 too, but it is not (same exception):

```
> "C:\Program Files\Java\jdk-13.0.1\bin\java.exe" -jar mcaselector-1.9.1.jar

Exception in thread "main" java.lang.NoClassDefFoundError: javafx/beans/property/StringProperty
        at net.querz.mcaselector.Config.setLocale(Config.java:87)
        at net.querz.mcaselector.Config.loadFromIni(Config.java:129)
        at net.querz.mcaselector.Main.main(Main.java:24)
Caused by: java.lang.ClassNotFoundException: javafx.beans.property.StringProperty
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 3 more
```

**Comment by aswheaton** [comment]
@0xfeeddeadbeef 

If you are using Oracle-brewed Java, then I think you are experiencing an issue separate from the one described in this thread, which is related to a missing part of the OpenJDK distribution of Java.

**Comment by 0xfeeddeadbeef** [comment]
@aswheaton I've just noticed that stack trace is different, I'll open a separate issue.
