### ISSUE TITLE
How do you change chunk biomes? 

### ISSUE THREAD

**Issue by PawoG04** [Querz/mcaselector#90]
I have been trying to change the chunk biomes but it does not work, help?

**Comment by Querz** [comment]
What have you tried so far?
What version of Minecraft did generate your world?

**Comment by PawoG04** [comment]
I have done the 
N.. thing, and it's 1.15.2

**Comment by PawoG04** [comment]
is that how you do it, or am I missing my brain?

**Comment by Querz** [comment]
It was a bug where the chunk location was calculated incorrectly. It has been fixed in [the latest release](https://github.com/Querz/mcaselector/releases/latest).

**Comment by PawoG04** [comment]
thanks

**Comment by PawoG04** [comment]
Still does not work, the chunk is the same, I deleted and change it to desert and nothing

**Comment by Querz** [comment]
Just tested it out, I can definitely change the biome of  a chunk in a 1.15.2 world. Can you tell me exactly what you do so i can reproduce your problem?

**Comment by PawoG04** [comment]
I was trying to make the chink a desert, I did it normally, and it still was badlands, then I deleted them and changed them there so they would gen desert and nothing.

**Comment by Sicarine** [comment]
Note that MCA selector cannot force minecraft to GENERATE a desert. Minecraft will always generate a badlands in that spot. What MCA selector allows you to do is to change the biome type on an **already generated** chunk. This means that you would SEE the blocks from a badlands there, but the game code would read desert, including its leaf coloration and lack of rainfall and propensity to spawn husks

**Comment by Querz** [comment]
As @Sicarine said, changing the biome of an already generated chunk does NOT change the blocks of that chunk. MCA Selector cannot influence how Minecraft generates chunks, it only works with existing data.

You could instead try to generate a desert (find a desert in a Minecraft world) and import it to where you want it to be in your world.
